# Generated by Django 4.2.6 on 2023-10-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ero_display_field", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ero_title",
            name="img",
            field=models.CharField(max_length=150, null=True, verbose_name="画像"),
        ),
    ]
